backend:
  name: github
  repo: sijan756/chandrasinghrana-personalwebsite  # GitHub repo
  branch: main
auth_type: implicit
  app_id: Ov23libKDOUCFMoOBANf                                     # branch to commit blogs

media_folder: "assets/images"  # uploaded images go here
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
